// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDym_M7eoa1a85QC3k56VXzx2XtjH0vGk0',
    appId: '1:647782038762:web:2acfedb44a894500d02b93',
    messagingSenderId: '647782038762',
    projectId: 'app-segura-1a29e',
    authDomain: 'app-segura-1a29e.firebaseapp.com',
    storageBucket: 'app-segura-1a29e.firebasestorage.app',
    measurementId: 'G-R1N8P29S2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBElG-LB-5SUQh2jHLMb7snD8p6TKPUkug',
    appId: '1:647782038762:android:20eda91dc310dcd8d02b93',
    messagingSenderId: '647782038762',
    projectId: 'app-segura-1a29e',
    storageBucket: 'app-segura-1a29e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6rZNOM6RSxZNE50B4WQBkpmzyv-RV3o',
    appId: '1:647782038762:ios:51377ce050b7e0c2d02b93',
    messagingSenderId: '647782038762',
    projectId: 'app-segura-1a29e',
    storageBucket: 'app-segura-1a29e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL6rZNOM6RSxZNE50B4WQBkpmzyv-RV3o',
    appId: '1:647782038762:ios:51377ce050b7e0c2d02b93',
    messagingSenderId: '647782038762',
    projectId: 'app-segura-1a29e',
    storageBucket: 'app-segura-1a29e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDym_M7eoa1a85QC3k56VXzx2XtjH0vGk0',
    appId: '1:647782038762:web:237b50ec06bc6b10d02b93',
    messagingSenderId: '647782038762',
    projectId: 'app-segura-1a29e',
    authDomain: 'app-segura-1a29e.firebaseapp.com',
    storageBucket: 'app-segura-1a29e.firebasestorage.app',
    measurementId: 'G-0HV7EZW02S',
  );
}
